version: '2'
services:
  site:
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - /var/local/blog.kelu.org:/srv/jekyll
      - /var/local/blog.kelu.org/vendor/bundle:/usr/local/bundle
      - /tmp/blog.kelu.org:/srv/jekyll/_site
    ports:
      - '34000:4000'
      - '34001:35729'
      - '34002:3000'
